---
title: "Warriors"
output:
  pdf_document: default
  html_document: default
date: "2023-02-27"
---
```{r}
# Loading the database
data = read.csv("DS2010_Warriors_Data.csv")
```

```{r}
# Saving the important columns into variable data
data <- data[, -c(1, 3, 5, 25:41)]
```

```{r}
# Making win(1) or loss(0) ---- 1 or 0
data$WL <- ifelse(data$WL == "W", 1, 0)
```

```{r}
# Making X column "HomeAway" into 1 or 0 ---- home(1) / away(0)
colnames(data)[2] <- "HomeAway"
data$HomeAway <- ifelse(data$HomeAway == "@", 0, 1)
```

```{r}
library('corrr')
library(ggplot2)
library(ggcorrplot)
library("FactoMineR")

# Normalizing the data
numerical_data <- data[,5:21]
head(numerical_data)


data_normalized <- scale(numerical_data)
head(data_normalized)
```

```{r}
#Compute the correlation matrix

corr_matrix <- cor(data_normalized)
ggcorrplot(corr_matrix)
```

```{r}
# Applying PCA

data.pca <- princomp(corr_matrix)

#Cumulative Proportion
summary(data.pca)
```

```{r}
# Visualization of the principal components

library(factoextra)
library(vctrs)

data.pca$loadings[, 1:17]
```

```{r}
# Scree Plot
fviz_eig(data.pca, addlabels = TRUE)
```

```{r}
# Biplot of the attributes
fviz_pca_var(data.pca, col.var = "black")
```

```{r}
# Biplot combined with cos2 
fviz_pca_var(data.pca, col.var = "cos2",
             gradient.cols = c("black", "orange", "green"),
             repel = TRUE)
```

```{r}
# Select the top 9 contributing variable
fviz_pca_var(data.pca, select.var = list(contrib = 9))
```

```{r}
# Regression Tree Part

library(rpart)
library(rpart.plot)
fit.tree = rpart(Tm ~ FG+AST+X3PPercentage+X3P+FGPercentage+FT+FTA+FGA+ORB, data=data, method="anova", control = list(cp = 0, xval = 9))
#summary(fit.tree)
fit.tree

rpart.plot(fit.tree)
```

```{r}
plotcp(fit.tree)
```



